### ISSUE TITLE
Your encode output so big (

### ISSUE THREAD

**Issue by retyui** [chrisboakes/postcss-encode-background-svgs#1]
Please read this post about [svg optimization](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris)
```css
.input{
     background-image: url('data:image/svg+xml, <svg xmlns="http://www.w3.org/2000/svg" /></svg>');
}

.output-your-plugin{
     background-image: url('data:image/svg+xml, %3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20%2F%3E%3C%2Fsvg%3E'); /* soo big */
}

.output-optimized{
     background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3C/svg%3E");
}
```
